global:
  account: '649999766497'
  region: 'us-east-1'
  common_prefix: 'sf-fw'
  env: 'poc'
  tags:
    owner: 'EPWERY'
    project: 'SalesForce Flowise PoC'
    env: 'poc'
    contact: 'lmv.vidal@gmail.com'

networking:
  vpc_cidr: '172.33.0.0/16'
  az_count: 2
  public_subnet_name: 'PublicSubnet'
  public_subnet_prefix: 20
  private_subnet_name: 'PrivateSubnet'
  private_subnet_prefix: 20
  isolated_subnet_name: 'IsolatedSubnet'
  isolated_subnet_prefix: 20

security:
  pgres_port: 5432
  cf_prefix_list: 'pl-3b927c52'
  local_ip: '152.168.252.102/32'

database:
  database_name: 'epwery'

compute:
  ec2_machine_type: 't2.micro'
  ebs_device_name: '/dev/xvda'
  event_bus_arn: 'arn:aws:events:us-east-1:649999766497:event-bus/aws.partner/salesforce.com/00Daj00000C74U9EAJ/0YLaj0000000LkPGAU'
  lambda_envvars:
    BASE_URL_SF: 'https://sturla3-dev-ed.develop.my.salesforce.com'
    BUCKET_NAME: 'sf-fw-poc-files'
    BUCKET_PATH_EXTXT: 'salesforce_extracted' # extracted text folder
    BUCKET_PATH_FW_DS: 'flowise_doc_store'    # flowise document store folder
    EXTRACT_TEXT: 'False'
    DYNAMODB_TABLE_NAME: 'sf-fw-poc-extxt-table'
    FILE_DOWNLOAD_PATH: 'services/data/v61.0/connect/files'
    SECRET_SF_CREDS_NAME: 'sf-fw-poc-connected-app-creds'
    SECRET_FW_CREDS_NAME: 'sf-fw-poc-fw-api-key'
    FW_CHATFLOW: '5f53ddcf-a8e0-4bd9-a707-0283bf4b0c51'

s3:
  # no values yet

access:
  pgres_port: 5432
  cache_policy_be: 'disabled'
  cache_policy_ui: 'disabled'
