global:
  account: '649999766497'
  region: 'us-east-1'
  common_prefix: 'sf-fw'
  env: 'poc'
  tags:
    owner: 'EPWERY'
    project: 'SalesForce Flowise PoC'
    env: 'poc'
    contact: 'lmv.vidal@gmail.com'

networking:
  vpc_cidr: '172.33.0.0/16'
  az_count: 2
  public_subnet_name: 'PublicSubnet'
  public_subnet_prefix: 20
  private_subnet_name: 'PrivateSubnet'
  private_subnet_prefix: 20
  isolated_subnet_name: 'IsolatedSubnet'
  isolated_subnet_prefix: 20

security:
  pgres_port: 5432
  cf_prefix_list: 'pl-3b927c52'
  local_ip: '152.168.151.136/32'

database:
  database_name: 'epwery'

s3:
  # no values yet

compute:
  ec2_machine_type_fw: 't3a.micro'
  ec2_machine_type_wa: 't3a.medium'
  ec2_machine_ami: 'ami-012967cc5a8c9f891'
  ebs_device_name: '/dev/xvda'
  event_bus_arn: 'arn:aws:events:us-east-1:649999766497:event-bus/aws.partner/salesforce.com/00Daj00000C74U9EAJ/0YLaj0000000LkPGAU'
  lambda_envvars_common:
    COMMON_PREFIX: 'sf-fw'
    ENV: 'poc'
    BUCKET_NAME: 'sf-fw-poc-files'
    BUCKET_PATH_FW_DS: 'flowise_doc_store'    # flowise document store folder
    SECRET_FW_CREDS_NAME: 'sf-fw-poc-fw-api-key'
    FW_CHATFLOW: 'Salesforce QnA Chatflow'
  lambda_envvars_process:
    BASE_URL_SF: 'https://sturla3-dev-ed.develop.my.salesforce.com'
    FILE_DOWNLOAD_PATH: 'services/data/v61.0/connect/files'
    SECRET_SF_CREDS_NAME: 'sf-fw-poc-connected-app-creds'
    SUPPORTED_FORMATS: '[".json", ".txt", ".csv", ".docx", ".xlsx", ".pdf", ".aspx", ".asp", ".cpp", ".c", ".cs", ".css", ".go", ".h", ".kt", ".java", ".js", ".less", ".ts", ".php", ".proto", ".python", ".py", ".rst", ".ruby", ".rb", ".rs", ".scala", ".sc", ".scss", ".sol", ".sql", ".swift", ".markdown", ".md", ".tex", ".ltx", ".html", ".vb", ".xml"]'
    SUPPORTED_FORMATS_IMG: '[".bmp", ".jpg", ".jpeg", ".png", ".tiff", ".gif", ".webp", ".heic", ".heif", ".ico", ".pcx"]'
  lambda_envvars_graph:
    TEST: 'TEST'
  lambda_envvars_tools:
    TEST: 'TEST'

access:
  pgres_port: 5432
  cache_policy_be_fw: 'disabled'
  cache_policy_ui_fw: 'disabled'
  cache_policy_be_wa: 'disabled'
  cache_policy_ui_wa: 'disabled'
